### ISSUE TITLE
getTickLength

### ISSUE THREAD

**Issue by ohmycode** [superjohan/conform#1]
Hey Johan,

thank you for sharing this project, it helped me a lot getting started with TAAE, and the app itself is inspiring stuff! I spend like an hour or so playing around with it :)

Now I'm trying to put together a simple sequencer on my own using your ConformSequencer class, and I got stuck with the getTickLength helper function and it's call from the ConformSequencerChannel.

I'm hoping you can point out to me what you're doing here:

tickLength = (samplingRate / 8.0) \* (120.0 / bpm);

I'm new to audio development, so probably I'm wrong, but this is how I undertand it:
tickLength is the amount of samples to be played in the given amount of time that a eighth note takes at a given speed. So that would explain "samplingRate", "8.0", and "bpm". but then what is "120" for?

The problem I'm running into is when I apply a time stretch filter to a channel, the ticklength varies, and the tempo messes up:

```
AEAudioUnitFilter *stretch
    = [[AEAudioUnitFilter alloc]
       initWithComponentDescription:AEAudioComponentDescriptionMake(kAudioUnitManufacturer_Apple,
                                                                    kAudioUnitType_FormatConverter,
                                                                    kAudioUnitSubType_NewTimePitch)
       audioController:_audioController
       error:&error];

AudioUnitSetParameter(stretch.audioUnit,
                                      kNewTimePitchParam_Rate,
                                      kAudioUnitScope_Global,
                                      0,
                                      2, // play at double speed
                                      0);
```

So I'm trying no normalize the getTickLength function in order to keep the BPM in time.

**Comment by ohmycode** [comment]
After writing this I just realized that it's as simple as multiplying tickLength with the value of the stretch filter.
But it would still be helpful to know what the function does exactly :)

**Comment by superjohan** [comment]
Honestly, I'm not really sure what's happening in the function, since I'm pretty sure it's a result of trial and error. :) It's been several months since I've done any audio programming as well. But I guess the thought behind the hardcoded 120.0 is that it's some kind of "base" bpm or something. Now that you got me thinking about it, I feel like the function could be rewritten to make more sense somehow. Especially considering that the ticks are 16th notes, not 8ths. :)
